version: '3.8'

services:
  news-aggregator:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
        - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
        - VITE_NYT_API_KEY=${VITE_NYT_API_KEY}
    container_name: modern-news-aggregator
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - news-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  news-aggregator-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: modern-news-aggregator-dev
    ports:
      - "5174:5174"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_NEWS_API_KEY=${VITE_NEWS_API_KEY}
      - VITE_GUARDIAN_API_KEY=${VITE_GUARDIAN_API_KEY}
      - VITE_NYT_API_KEY=${VITE_NYT_API_KEY}
    command: npm run dev
    restart: unless-stopped
    networks:
      - news-network
    profiles:
      - dev

networks:
  news-network:
    driver: bridge